### ISSUE TITLE
Failed to open data.sql

### ISSUE THREAD

**Issue by Firestorm980** [10up/wpsnapshots#20]
When running a pull request, an error can come up right after the database update comment (when running verbose):

`ERROR at line 1: Failed to open file '/{pathtofiles}/.wpsnapshots/data.sql', error: 2`

The issue seems to be that the download is `data.sql.gz`. Unzipping the archive and putting it into the hidden folder generated seems to fix the issue.

**Comment by tlovett1** [comment]
This should be fixed. Can you test?
