### ISSUE TITLE
Provide subdomain for multisite pull

### ISSUE THREAD

**Issue by ChaosExAnima** [10up/wpsnapshots#26]
When pulling a multisite installation, the system provides path information but not subdomain information. For example:

> Multisite installation (subdomain based install) detected.
> Replacing URLs for blog 1. Path for blog is /.
> Domain (localhost.dev for example):
> [snip]
> Replacing URLs for blog 3. Path for blog is /.
> Domain (localhost.dev for example):

I would propose the system also reads the `domain` column of `wp_blogs` to provide output similar to the following (bold added for emphasis):

> Multisite installation (subdomain based install) detected.
> Replacing URLs for blog 1. Path for blog is /**, domain is sub1.localhost.dev**.
> Domain (localhost.dev for example):

**Comment by tlovett1** [comment]
Yep, this makes sense. I'll add. Thanks!

**Comment by tlovett1** [comment]
Added!
