### ISSUE TITLE
Error on wpsnapshots create-repository

### ISSUE THREAD

**Issue by EvanAgee** [10up/wpsnapshots#30]
When I run `wpsnapshots create-repository` I'm getting the following error:

![image](https://user-images.githubusercontent.com/1692674/38946278-95032120-42fe-11e8-8515-7e4a86cf3c46.png)

Which is triggered by this line:
![image](https://user-images.githubusercontent.com/1692674/38946338-c28014be-42fe-11e8-901a-28926dc3bdc4.png)

**Comment by EvanAgee** [comment]
I discovered that wpsnapshots has since been rolled into [wp-local-docker](https://github.com/10up/wp-local-docker) and thought that was likely my issue, but alas:

![image](https://user-images.githubusercontent.com/1692674/38946645-b33e98a8-42ff-11e8-898c-35df65792df9.png)

**Comment by tlovett1** [comment]
Hmmm that definitely seems like a bug. However, you shouldn't need to run this.
