### ISSUE TITLE
suggestion: move/delete mu-plugins

### ISSUE THREAD

**Issue by krisgale** [10up/wpsnapshots#32]
WPE's platform-specific plugins clog up / ruin the works on a local environment... could be solved by adding `mv mu-plugins __mu-plugins` when doing a pull

**Comment by tlovett1** [comment]
Maybe just delete them on a pull?

**Comment by cmmarslender** [comment]
There are plenty of sites that have valid mu-plugins that we wouldn't want to delete. If we're creating a snapshot from a local environment, presumably we've already deleted these plugins and they wont be part of the snapshot?

**Comment by krisgale** [comment]
i'm closing this issue, as i've come to understand 'mu' is 'must-use' not the prior 'multiuser/multisite' paradigm it once was... this has definitely has since revealed itself to be a naive suggestion.
