### ISSUE TITLE
Install issues: symfony/console package version

### ISSUE THREAD

**Issue by colorful-tones** [10up/wpsnapshots#35]
I just tried to install WP Snapshots.

I ran: 
```
composer global config repositories.wpsnapshots vcs https://github.com/10up/wpsnapshots
```

and then: 
```
composer global require 10up/wpsnapshots:dev-master -n
```

Which gave me an error: `Your requirements could not be resolved to an installable set of packages.`

I'm attaching full screenshot of output. 

Does this mean I have to downgrade my `symfony/console` package? I run `composer show global` and see: `symfony/console v4.1.3  Symfony Console Component`

![screenshot 2018-08-02 11 24 52](https://user-images.githubusercontent.com/405912/43594172-91780d12-9647-11e8-88e9-00112d7e6c15.png)

**Comment by christianc1** [comment]
@colorful-tones 

The composer dependency manifest for this project is looking for [`^3.3`](https://github.com/10up/wpsnapshots/blob/fa31d9a55ea83d92c5a0ed275b4d9cdba52c1b64/composer.json#L13) of the `symfony/console` package.  The `^` version constraint resolves `>=3.3` but `<4.0.0`.  

Perhaps the version required by wpsnapshots will satisfy the requirements of whatever other package is requiring `symfony/console`.  You can run `composer global why symfony/console` to see what package installed it at `v4.1.3`.

In addition, we should confirm compatibility with `v4.x` of `symfony/console` and potentially update the composer manifest.

**Comment by colorful-tones** [comment]
@christianc1 

I ran `composer global why symfony/console` and PHPCS Fixer is the culprit, which I would think is a common package?

```
friendsofphp/php-cs-fixer  v2.12.2  requires  symfony/console (^3.2 || ^4.0)
```

**Comment by colorful-tones** [comment]
Oh, but not looking closer at the output: `(^3.2 || ^4.0)`. I looks like PHPCS Fixer is saying is supports me downgrading to 3.*

I'll dig in and see if I can reinstall or downgrade. If you happen to be more adept at composer then feel free to post commands for doing so.

Thanks!

**Comment by colorful-tones** [comment]
Ha, I just did:
1. `composer global remove symfony/console`
2. `composer global require symfony/console:3.3`
3. `composer global require 10up/wpsnapshots:dev-master -n`

And it worked fine, but then went in to a call. I'll now go back to `symfony/console` 4.* and pull in latest Snapshots and test. Thanks!

**Comment by colorful-tones** [comment]
Everything work fine now with #36 merged. Thanks @christianc1
