### ISSUE TITLE
When installing a multisite snapshot, wp_blogs does not update correctly.

### ISSUE THREAD

**Issue by gthayer** [10up/wpsnapshots#39]
When importing a multisite, the search/replace does not properly update the wp_blogs table. Instead, it sets the hostname for each site to the multisite's default domain.

Search/replace within the various blog's DB tables appears to update correctly.

**Comment by tlovett1** [comment]
@gthayer can you test the latest version of `master`? Just pushed a new version which hopefully fixes this.

**Comment by cmmarslender** [comment]
Latest version fixed the issue for me.

**Comment by gthayer** [comment]
@tlovett1 Looks good to me also. I think this also resolves this ticket: https://github.com/10up/wpsnapshots/issues/38

Thanks a lot!
