### ISSUE TITLE
Cannot push/create snapshot

### ISSUE THREAD

**Issue by eflorea** [10up/wpsnapshots#43]
When running wpsnapshots push I get an exception error message:
The "exclude-uploads" option does not exist.  

Looking at the code there are some inconsistency using the exclude_uploads vs exclude-uploads.

<img width="988" alt="screen shot 2018-10-07 at 12 26 10 pm" src="https://user-images.githubusercontent.com/13055601/46585937-4e8c7600-ca2c-11e8-9019-f33dcd0fef0c.png">

<img width="875" alt="screen shot 2018-10-07 at 12 26 22 pm" src="https://user-images.githubusercontent.com/13055601/46585943-551aed80-ca2c-11e8-8837-5a96da6129a9.png">

**Comment by eflorea** [comment]
https://github.com/10up/wpsnapshots/pull/44

**Comment by jeffpaul** [comment]
@eflorea based on @tlovett1's [comment](https://github.com/10up/wpsnapshots/pull/44#issuecomment-427712229) it looks like this may be resolved.  Would you please re-test and confirm if this is resolved or provide additional information if you're still seeing this issue?  Thanks!
