### ISSUE TITLE
Feature Request: Add flag to scrub emails

### ISSUE THREAD

**Issue by ChaosExAnima** [10up/wpsnapshots#46]
Add a way to scrub emails on upload and/or download of database, just as we scrub passwords.

**Comment by tlovett1** [comment]
Love this idea.

**Comment by ChaosExAnima** [comment]
@tlovett1 - Thanks! Hoping to get a PR to you today.

CC @TheLastCicada

**Comment by cmmarslender** [comment]
I think maybe this should be default behavior, and if we want to have a flag for anything, maybe the flag is just to prevent it from happening?

**Comment by ChaosExAnima** [comment]
@cmmarslender - Do we want to include this flag under `--no_scrub`?
