### ISSUE TITLE
Create Repo failing

### ISSUE THREAD

**Issue by Bonsaikitt3n** [10up/wpsnapshots#51]
AWS client and access are working with the right perms. 

WP Snapshots configuration verified and saved.
octagon@hax ~/c/w/updato-test> 10updocker wpsnapshots create-repository dood
Ensuring global network exists
 - Network exists
Ensuring global cache volume exists
 - Creating Volume
Ensuring global services are running
global_mailcatcher_1 is up-to-date
global_dns_1 is up-to-date
global_mysql_1 is up-to-date
global_gateway_1 is up-to-date
global_phpmyadmin_1 is up-to-date
Waiting for mysql...

Checking USER ID
Host user is 0:0

                                          
  The "--db_user" option does not exist.  
                                          

create-repository <repository>

octagon@hax ~/c/w/updato-test>

**Comment by tlovett1** [comment]
@Bonsaikitt3n this appears to be an issue with WP Local Docker. For you, you could try setting up the repo on your host machine `composer global require 10up/wpsnapshots`.

@cmmarslender mind taking a look? I get that same error when I run `10updocker wpsnapshots -v`

**Comment by Bonsaikitt3n** [comment]
The vanilla install of wpsnapshots seems to create repo. I'm guessing the issue is in:

https://github.com/10up/wp-local-docker-v2/blob/ced12191f8dfe5f3f79369a309ce8d25c6dc4dc4/src/wpsnapshots.js#L62

If I have a sec I will test what happens with the --db_user=root taken out of that command

**Comment by Bonsaikitt3n** [comment]
Nope, I lied. S3 bucket was created in us-west-1, failed silently on the dynamoDB create table. The command did go through though and said repo created. Maybe have a check at the end that the resources actually exist.

**Comment by Bonsaikitt3n** [comment]
Sorry, being so chatty in here. Turns out the dynamoDB failure was because of the state of the current existing repo and the failures of using this with the 10updocker v2. I went back with the vanilla client and re-created the original repo name and created the dynamo resource. This thing gets in weird states if there is that error caused by the v2 wrapper.

**Comment by cmmarslender** [comment]
The WP Local Docker issues are resolved in version 2.4.3 ( https://github.com/10up/wp-local-docker-v2/commit/6ba0d748aa42a96045151388d567987320e1eaa3 )
