### ISSUE TITLE
Multisite User Scrubbing

### ISSUE THREAD

**Issue by TylerB24890** [10up/wpsnapshots#65]
**Describe the bug**
When running `wpsnapshots push` on a multisite installation an error occurs "`mysqldump: Couldn't find table: "wp_2_users_temp"`" at the `Exporting database... \n Scrubbing users...` step. WP Multisite doesn't have individual `wp_users` tables per site, so attempting to fill `wp_2_users_temp` from `wp_2_users` is an invalid operation.

**Steps to Reproduce**
1. Run `wpsnapshots push` on a multisite installation
2. Fill out the snapshot information as required
3. `Include files in snapshot?` **N**
4. `include database in snapshot?` **Y**
5. Wait for export to begin and validate if it completes or not.

**Expected behavior**
Upon running the steps above, I expected WP Snapshots to return the newly created snapshot ID containing the exported and scrubbed database for the multisite installation.

**Screenshots**
![Screen Shot 2020-07-22 at 12 09 57 PM](https://user-images.githubusercontent.com/1687128/88200771-9afe7100-cc14-11ea-80f2-da8176aff340.png)

**Environment information**
 - Device: Macbook Pro
 - OS: macOS Mojave 10.14.6
 - WordPress version: 5.4.2
 
 - <details><summary>Site Health Info:</summary>
   
   </details>

**Additional context**
This is occurring from WP Local Docker V2 (2.7) on a WP Multisite Subdirectory installation.

**Comment by felipeelia** [comment]
I am able to reproduce it too.
